### ISSUE TITLE
APK? 

### ISSUE THREAD

**Issue by Aymkdn** [apsun/Cardapter#1]
Hi,

Once enabled unknown sources in the developer settings menu of Android Auto, I guess I have to download and install your APK? I don't see any compiled app of Caradapter, but only the sources...

Any help would be welcomed about the next steps!

Thanks

**Comment by apsun** [comment]
It's on the releases page: https://github.com/apsun/Cardapter/releases/tag/v1.0.0

**Comment by Aymkdn** [comment]
Thank you!
